

export const CodeTable = [
  {"keyCode":32, "keyLabel":[ " " , " " ]},
  {"keyCode":48, "keyLabel":[ "0" , "" ]},
  {"keyCode":49, "keyLabel":[ "1" , "!" ]},
  {"keyCode":50, "keyLabel":[ "2" , "\"" ]},
  {"keyCode":51, "keyLabel":[ "3" , "#" ]},
  {"keyCode":52, "keyLabel":[ "4" , "$" ]},
  {"keyCode":53, "keyLabel":[ "5" , "%" ]},
  {"keyCode":54, "keyLabel":[ "6" , "&" ]},
  {"keyCode":55, "keyLabel":[ "7" , "'" ]},
  {"keyCode":56, "keyLabel":[ "8" , "(" ]},
  {"keyCode":57, "keyLabel":[ "9" , ")" ]},
  {"keyCode":59, "keyLabel":[ ":" , "+" ]},
  {"keyCode":65, "keyLabel":[ "A" , "A" ]},
  {"keyCode":66, "keyLabel":[ "B" , "B" ]},
  {"keyCode":67, "keyLabel":[ "C" , "C" ]},
  {"keyCode":68, "keyLabel":[ "D" , "D" ]},
  {"keyCode":69, "keyLabel":[ "E" , "E" ]},
  {"keyCode":70, "keyLabel":[ "F" , "F" ]},
  {"keyCode":71, "keyLabel":[ "G" , "G" ]},
  {"keyCode":72, "keyLabel":[ "H" , "H" ]},
  {"keyCode":73, "keyLabel":[ "I" , "I" ]},
  {"keyCode":74, "keyLabel":[ "J" , "J" ]},
  {"keyCode":75, "keyLabel":[ "K" , "K" ]},
  {"keyCode":76, "keyLabel":[ "L" , "L" ]},
  {"keyCode":77, "keyLabel":[ "M" , "M" ]},
  {"keyCode":78, "keyLabel":[ "N" , "N" ]},
  {"keyCode":79, "keyLabel":[ "O" , "O" ]},
  {"keyCode":80, "keyLabel":[ "P" , "P" ]},
  {"keyCode":81, "keyLabel":[ "Q" , "Q" ]},
  {"keyCode":82, "keyLabel":[ "R" , "R" ]},
  {"keyCode":83, "keyLabel":[ "S" , "S" ]},
  {"keyCode":84, "keyLabel":[ "T" , "I" ]},
  {"keyCode":85, "keyLabel":[ "U" , "U" ]},
  {"keyCode":86, "keyLabel":[ "V" , "V" ]},
  {"keyCode":87, "keyLabel":[ "W" , "W" ]},
  {"keyCode":88, "keyLabel":[ "X" , "X" ]},
  {"keyCode":89, "keyLabel":[ "Y" , "Y" ]},
  {"keyCode":90, "keyLabel":[ "Z" , "Z" ]},
 {"keyCode":107, "keyLabel":[ ";" , "+" ]},
 {"keyCode":109, "keyLabel":[ "-" , "=" ]},
 {"keyCode":186, "keyLabel":[ ":" , "*" ]},
 {"keyCode":187, "keyLabel":[ ";" , "+" ]},
 {"keyCode":188, "keyLabel":[ "," , "<" ]},
 {"keyCode":189, "keyLabel":[ "-" , "=" ]},
 {"keyCode":190, "keyLabel":[ "." , ">" ]},
 {"keyCode":191, "keyLabel":[ "/" , "?" ]},
 {"keyCode":192, "keyLabel":[ "@" , "`" ]},
 {"keyCode":219, "keyLabel":[ "[" , "{" ]},
 {"keyCode":220, "keyLabel":[ "\\", "|" ]},
 {"keyCode":221, "keyLabel":[ "]" , "}" ]},
 {"keyCode":222, "keyLabel":[ "^" , "~" ]},
 {"keyCode":226, "keyLabel":[ "\\", "_" ]}
]
